name: Print Name and Date

on:
  push

jobs:
  print-details:
    runs-on: ubuntu-latest

    steps:
      - name: Print Name
        run: echo "My name is Sri Lakshmi"


      - name: Run Docker Version
        run: docker --version

      - name: Print Date
        run: date